# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-2-Clause

---
#tasks file for roles/catalogs

#################################### Create ##########################################################################
- name: create catalog
  vcd_catalog:
    user: 'XXXXXXXXXX'
    org: 'XXXXXXXXXX'
    password: 'XXXXXXXXXX'
    host: 'XXXXXXXXXX'
    catalog_name: "{{ catalog_name }}"
    description: "{{ description }}"
    state: "present"
  register: output

- name: create catalog output
  debug:
    msg: '{{ output }}'

#################################### Read-Catalog ##########################################################################

- name: read catalog
  vcd_catalog:
    user: 'XXXXXXXXXX'
    org: 'XXXXXXXXXX'
    password: 'XXXXXXXXXX'
    host: 'XXXXXXXXXX'
    catalog_name: "{{ catalog_name }}" 
    operation: "read"
  register: output

- name: Read catalog output
  debug:
    msg: '{{ output }}'


#################################### Update-Name-And description ##########################################################################

- name: update catalog name and description
  vcd_catalog:
    user: 'XXXXXXXXXX'
    org: 'XXXXXXXXXX'
    password: 'XXXXXXXXXX'
    host: 'XXXXXXXXXX'
    catalog_name: "{{ catalog_name }}" 
    new_catalog_name: "{{ new_catalog_name }}" 
    description: "{{ description }}"
    state: "update"
  register: output

- name: Update Catalog name and description output
  debug:
    msg: '{{ output }}'

#################################### shared/unshare-catalog ##########################################################################

- name: share/unshare catalog
  vcd_catalog:
    user: 'XXXXXXXXXX'
    org: 'XXXXXXXXXX'
    password: 'XXXXXXXXXX'
    host: 'XXXXXXXXXX'
    catalog_name: "{{ new_catalog_name }}" 
    shared: "{{ shared }}"
    operation: "shared"
  register: output

- name: share/unshare catalog output
  debug:
    msg: '{{ output }}'

#################################### Delete ##########################################################################
- name: delete catalog
  vcd_catalog:
    user: 'XXXXXXXXXX'
    org: 'XXXXXXXXXX'
    password: 'XXXXXXXXXX'
    host: 'XXXXXXXXXX'
    catalog_name: "{{ new_catalog_name }}"
    state: "absent"
  register: output

- name: delete catalog output
  debug:
    msg: '{{ output }}' 

#################################### List items ##########################################################################
- name: list catalog items
  vcd_catalog:
    user: 'XXXXXXXXXX'
    org: 'XXXXXXXXXX'
    password: 'XXXXXXXXXX'
    host: 'XXXXXXXXXX'
    catalog_name: "{{ new_catalog_name }}"
    operation: "list_items"
  register: output

- name: list catalog items output
  debug:
    msg: '{{ output }}'
