# Copyright © 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-2-Clause

---
# tasks file for roles/catalog_item

############################################ upload-media ##############################################################
- name: upload media
  vcd_catalog_item:
    catalog_name: "{{ catalog_name }}"
    item_name: "{{ media_item_name }}"
    file_name : "{{ media_file_name }}"
    chunk_size: "{{ chunk_size }}"
    state: "present"
  register: output

- name: upload media output
  debug:
    msg: '{{ output }}'  

# ############################################ delete-media ##############################################################
- name: delete media
  vcd_catalog_item:
    catalog_name: "{{ catalog_name }}"
    item_name: "{{ media_item_name }}"
    state: "absent"
  register: output

- name: delete media output
  debug:
    msg: '{{ output }}'  


############################################ upload-ova ##############################################################
- name: upload ova
  vcd_catalog_item:
    user: 'XXXXXXXXXX'
    org: 'XXXXXXXXXX'
    password: 'XXXXXXXXXX'
    host: 'XXXXXXXXXX'
    catalog_name: "{{ catalog_name }}"
    item_name: "{{ ova_item_name }}"
    file_name : "{{ ova_file_name }}"
    chunk_size: "{{ chunk_size }}"
    state: "present"
  register: output

- name: upload ova output
  debug:
    msg: '{{ output }}'

############################################ delete-ova ##############################################################
- name: delete ova
  vcd_catalog_item:
    catalog_name: "{{ catalog_name }}"
    item_name: "{{ ova_item_name }}"
    state: "absent"
  register: output

- name: delete ova output
  debug:
    msg: '{{ output }}'  

############################################ capture-vapp ##############################################################
- name: capture vapp
  vcd_catalog_item:
    user: 'XXXXXXXXXX'
    org: 'XXXXXXXXXX'
    password: 'XXXXXXXXXX'
    host: 'XXXXXXXXXX'
    catalog_name: "{{ catalog_name }}"
    item_name: "{{ capture_vapp_item_name }}"
    vapp_name: "{{ vapp_name }}"
    vdc_name: "{{ vdc_name }}"
    description: "{{ description }}"
    customize_on_instantiate: "{{ customize_on_instantiate }}"
    overwrite: "{{ overwrite }}"
    operation: "capturevapp"
  register: output

- name: capture vapp output
  debug:
    msg: '{{ output }}'  

############################################ delete-capture-vapp ##############################################################
- name: delete capture-vapp
  vcd_catalog_item:
    user: 'XXXXXXXXXX'
    org: 'XXXXXXXXXX'
    password: 'XXXXXXXXXX'
    host: 'XXXXXXXXXX'
    catalog_name: "{{ catalog_name }}"
    item_name: "{{ capture_vapp_item_name }}"
    state: "absent"
  register: output

- name: delete capture-vapp output
  debug:
    msg: '{{ output }}'

############################################ list-vms ##############################################################
- name: list catalog item vms
  vcd_catalog_item:
    user: 'XXXXXXXXXX'
    org: 'XXXXXXXXXX'
    password: 'XXXXXXXXXX'
    host: 'XXXXXXXXXX'
    catalog_name: "{{ catalog_name }}"
    item_name: "{{ capture_vapp_item_name }}"
    operation: "list_vms"
  register: output

- name: list catalog item vms output
  debug:
    msg: '{{ output }}'
