---
# tasks file for roles/vappvmdisk
- name: create vapp vm disk
  vcd_vapp_vm_disk:
    vm_name: "Tiny Linux template"
    vapp: "web2"
    vdc: "ACME_PAYG"
    size: "12000"
    state: "present"
  register: output

- name: create vapp vm disk output
  debug:
    msg: '{{ output }}'

- name: read vapp vm disks
  vcd_vapp_vm_disk:
    vm_name: "Tiny Linux template"
    vapp: "web2"
    vdc: "ACME_PAYG"
    operation: "read"
  register: output

- name: read vapp vm disks output
  debug:
    msg: '{{ output }}'


# - name: update disk
#   vcd_vapp_vm_disk:
#     vm_name: "Tiny Linux template"
#     vapp: "web2"
#     vdc: "ACME_PAYG"
#     disk_name: "Hard disk 3"
#     size: "13000"
#     state: "update"
#   register: output

# - name: update disk output
#   debug:
#     msg: '{{ output }}'

- name: delete disk
  vcd_vapp_vm_disk:
    vm_name: "Tiny Linux template"
    vapp: "web2"
    vdc: "ACME_PAYG"
    disks:
      - 'Hard disk 3'
      - 'Hard disk 4'
    state: "absent"
  register: output

- name: delete disk output
  debug:
    msg: '{{ output }}'
