# ---
# # tasks file for roles/user

- name: create user
  no_log: False
  vcd_user:
    username: "{{ username }}"
    userpassword: test_password
    role_name: "Organization Administrator"
    state: "present"
  register: output

- name: create user output
  debug:
    msg: '{{ output }}'

- name: update user
  no_log: False
  vcd_user:
    username: "{{ username }}"
    is_enabled: "true"
    state: "update"
  register: output

- name: update user output
  debug:
    msg: '{{ output }}'

- name: delete user
  no_log: False
  vcd_user:
    username: "{{ username }}"
    state: "absent"
  register: output

- name: delete user output
  debug:
    msg: '{{ output }}'
